### PR TITLE
cereal

### PR DESCRIPTION
**Pull request by smw150430**
Am I doing this correctly?

### CODE REVIEW

**Review by enkeboll — CHANGES_REQUESTED** [review]
you've added a url, but not embedded an image! use the Markdown syntax to show the image in the file

**Comment by smw150430** [comment]
I think I fixed it?

**Comment by enkeboll** [comment]
not quite--
1. gotta keep the pull request open if you want it to get merged
2. the syntax is `Alt Text`

**Comment by smw150430** [comment]
To Andy,

Crap. If there isn't a practical reason for me to fix this blunder, then
I'll leave you to your vacation. I apologize for the inconvenience.

Sincerely,
Stephen

**Pull request closed without merging**
